### ISSUE TITLE
How do we instrumented method's arguments changing?

### ISSUE THREAD

**Issue by MrAlias** [open-telemetry/opentelemetry-go-instrumentation#557]
A change to the internal and unexported `http2Server` type's method `operateHeaders` was included in the latest release of  `google.golang.org/grpc`:

https://github.com/grpc/grpc-go/pull/6716/files#diff-4058722211b8d52e2d5b0c0b7542059ed447a04017b69520d767e94a9493409eR334

This means our [lookup of the header field from arguments](https://github.com/open-telemetry/opentelemetry-go-instrumentation/blob/9b46e469c2e2c62a35352a3b0378c7a83390e5f5/internal/pkg/instrumentation/bpf/google.golang.org/grpc/server/bpf/probe.bpf.c#L129-L130) fails:

https://github.com/open-telemetry/opentelemetry-go-instrumentation/actions/runs/7183956908/job/19570460584

How can we address this in a backwards compatible way?

_Originally posted by @MrAlias in https://github.com/open-telemetry/opentelemetry-go-instrumentation/issues/555#issuecomment-1852910966_

**Comment by MrAlias** [comment]
cc @edeNFed @RonFed

**Comment by RonFed** [comment]
I think a quick solution for this can be injecting a boolean value to the gRPC-server eBPF probe which indicates whether we are working on a new gRPC version or not. Then we can change
```Go
u64 frame_pos = 2;
```
to
```C
u64 frame_pos = 2;
if (new_grpc) {
      frame_pos = 4;
}
```

A long term solution can be to add support for different Probes for versions of the same library. we may want to change the Probe interface adding a method declaring which versions of the instrumented library are supported by this probe. This change will give us more flexibility. It also makes sense in this case since adding the `context` to the gRPC function can make the eBPF code simpler for the newer versions.
