### ISSUE TITLE
Release v0.1.0-alpha

### ISSUE THREAD

**Issue by MrAlias** [open-telemetry/opentelemetry-go-instrumentation#66]
Blocking

- [x] https://github.com/open-telemetry/opentelemetry-go-instrumentation/pull/40

**Comment by damemi** [comment]
With #40 merged, are we set to tag the release?

**Comment by MrAlias** [comment]
Do we want to setup a [vanity URL](https://github.com/open-telemetry/opentelemetry-go-vanityurls) for this package before we release it?

It currently has a package of `github.com/open-telemetry/opentelemetry-go-instrumentation`, but all other OTel Go projects use `go.opentelemetry.io/`.

**Comment by MrAlias** [comment]
Maybe go.opentelemetry.io/auto?

**Comment by damemi** [comment]
Vanity url looks really cool, I don't have a big preference on the name but definitely +1 to setting it up

**Comment by TylerHelmuth** [comment]
@MrAlias need to open this back up as the [release workflow didn't pass](https://github.com/open-telemetry/opentelemetry-go-instrumentation/actions/runs/4724518902/jobs/8381827448).  Looks like our dockerhub token isn't properly setup

**Comment by TylerHelmuth** [comment]
Followed up with the original ticket to create the secretes here: https://github.com/open-telemetry/community/issues/1377

**Comment by MrAlias** [comment]
> If we don't want to wait I believe we could update the release workflow to only push to `ghcr.io`, but we'd have to do a new tag to rerun the workflow.

I'm okay waiting for the TC to try and create the repo.

**Comment by TylerHelmuth** [comment]
Think I should open a second ticket?  Technically the closed ticket I linked didn't asked for the repository to be made, only for the secrets.

**Comment by MrAlias** [comment]
> Think I should open a second ticket? Technically the closed ticket I linked didn't asked for the repository to be made, only for the secrets.

Yeah, that makes sense to me.

**Comment by TylerHelmuth** [comment]
New issue created: https://github.com/open-telemetry/community/issues/1442

**Comment by MrAlias** [comment]
@TylerHelmuth: https://github.com/open-telemetry/community/issues/1442 looks resolved, but the build is still failing:

https://github.com/open-telemetry/opentelemetry-go-instrumentation/actions/runs/4724518902/jobs/8406320441

**Comment by TylerHelmuth** [comment]
Ok I will keep investigating

**Comment by TylerHelmuth** [comment]
@MrAlias I tested this again with my own dockerhub credentials and [it worked as expected](https://github.com/TylerHelmuth/opentelemetry-go-instrumentation/actions/runs/4736098013/jobs/8407186671) :/

Can we check the `DOCKER_USERNAME` and `DOCKER_PASSWORD` secrets and ensure they are correct?

**Comment by TylerHelmuth** [comment]
I was able to reproduce the issue by generating a Read-only token and setting it for `DOCKER_PASSWORD`: https://github.com/TylerHelmuth/opentelemetry-go-instrumentation/actions/runs/4736205676/jobs/8407432789.  So I'm back to thinking the issue is the token itself.

**Comment by MrAlias** [comment]
> @MrAlias I tested this again with my own dockerhub credentials and [it worked as expected](https://github.com/TylerHelmuth/opentelemetry-go-instrumentation/actions/runs/4736098013/jobs/8407186671) :/
> 
> Can we check the `DOCKER_USERNAME` and `DOCKER_PASSWORD` secrets and ensure they are correct?

I don't have access to these settings. The TC would be the one with the access.

**Comment by TylerHelmuth** [comment]
@MrAlias the token has been recreated, can we retry the build?

**Comment by MrAlias** [comment]
https://github.com/open-telemetry/opentelemetry-go-instrumentation/actions/runs/4724518902/jobs/8410060528

**Comment by TylerHelmuth** [comment]
Pretty frustrating.  I'm feeling more inclined to strip out the DockerHub stuff for now.

**Comment by TylerHelmuth** [comment]
Any chance the action we're rerunning is caching the old token and we'd need a new instance of the action to see the new token value?

**Comment by TylerHelmuth** [comment]
> I wonder if the second docker login is messing things up.

Maybe, but unlikely, since they are independent logins.  The first instance of the `docker/login-action` action logs into DockerHub and the second instance logs into the `ghcr.io` registry. The DockerHub login uses the `DOCKER_USERNAME` and `DOCKER_PASSWORD` secrets and the `ghcr.io` login uses the GitHub context of the person who triggered the action.

For DockerHub login we'd be able to login even if the token doesn't have permission to push.

For the `ghcr.io` login I think we're following best practices, but since we haven't actually hit that step of the release yet we don't really know.  Looking at the [`opentelemetry-demo` repo](https://github.com/open-telemetry/opentelemetry-demo/blob/1e6c1f69aac824cb568da755c6177f16aa265c75/.github/workflows/release.yml#L91) we could use `username: ${{ github.repository_owner }}`  instead.

**Comment by TylerHelmuth** [comment]
@MrAlias I spent some more time this morning investigating how different OTel repositories publish images and it looks like us and the operator are the only ones that use the `docker/metadata-action` and the operator only pushing to ghcr.  I don't have any good theories right now as to why we are experiencing issues, especially since we are following [GitHub best practices](https://docs.github.com/en/actions/publishing-packages/publishing-docker-images#publishing-images-to-docker-hub-and-github-packages).  My guesses:
- Something is still wrong with the token (seems _very_ unlikely at this point since we have proof of a read/write token)
- We have issues pushing to `otel/autoinstrumentation-go` as the `otelbot` username based solely on [this comment](https://github.com/docker/build-push-action/issues/160#issuecomment-1102849307).  The DockerHub `otel` account is a Community Organization tho so I don't see why using a username that does not equal the namespace should matter.  This is a theory I can't test with my account since it only has 1 user.
- Something with specifying the tags in the the metadata action isn't playing nice with the `docker/build-push-action` action.  The `opentelemetry-demo` repository is able to push to both repositories but they don't use the metadata action, opting instead to specify the tags directly in the `docker/build-push-action` action.  The downside is that the demo images don't have all the labels we require.

With that information, how would you feel about removing the DockerHub stuff for now, creating an issue to add it back, and moving forward with only ghcr?  This aligns us with the only other repository using `metadata-action` action, still provides an image in an appropriate place with the appropriate labels, and allows us to move forward with this release and any future releases.

**Comment by damemi** [comment]
> Providing an image which didn't happen with 0.1.0-alpha

This is the key goal imo, +1 to another release

**Comment by MikeGoldsmith** [comment]
Yep, agree - even just to verify the release process successfully publishes an image would good. There are many in-flight PRs that improve the agent but another release when they're ready will be easier once we know the release process works as intended.

**Comment by robbkidd** [comment]
New Guy Input: release early, release often! Especially when it's `-alpha`. Exercise the evolving release pipeline and get changes out there to learn from closer-to-real-world consumption.

**Comment by pellared** [comment]
> Providing an image which didn't happen with 0.1.0-alpha

We can also create `0.1.1-alpha` so that we test the whole releasing processes.

**Comment by MrAlias** [comment]
We're resolving to "fail forward". Future releases will have a docker image.

See https://github.com/open-telemetry/opentelemetry-go-instrumentation/issues/131

**Comment by tigrannajaryan** [comment]
We may have found the reason why this didn't work, see the long thread: https://cloud-native.slack.com/archives/C033BJ8BASU/p1683062397439339

**Comment by MrAlias** [comment]
New job: https://github.com/open-telemetry/opentelemetry-go-instrumentation/actions/runs/4724518902/jobs/8812701237

**Comment by tigrannajaryan** [comment]
Worked? https://hub.docker.com/repository/docker/otel/autoinstrumentation-go/general

**Comment by MrAlias** [comment]
Yay! Seems like it to me.

**Comment by TylerHelmuth** [comment]
Woo! Now we can add back the DockerHub release stuff.
